name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    env:
      RUST_VERSION: '1.75.0'
    steps:
    - uses: actions/checkout@v4

    - name: Install
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true

    - name: Publish
      run: |
        cd src
        cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
        cargo publish --package aws-local
